application: cdac-mediasite
version: 1-3-0-jwts-stored-locally-for-login
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: 2.5.1
- name: ssl
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.APP

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/jspm_packages/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.md$
