"""
settings
"""

MEDIASITE_API_KEY = 'FDEOJERG4523DFOIP'
MEDIASITE_BASE_URL = 'http://api.media2.cdac.ca/'
MEDIASITE_SONGS_URL = MEDIASITE_BASE_URL + 'Songs/'
MEDIASITE_SEARCH_SONGS_URL = MEDIASITE_SONGS_URL + 'Search/'
